use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Source {
    Keyboard,
    Mouse,
    Cli,
}

impl Source {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Keyboard => "keyboard",
            Self::Mouse => "mouse",
            Self::Cli => "cli",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FeatureId {
    ToolbarNewSession,
    ToolbarSearch,
    ToolbarAutomations,
    ToolbarMcps,
    ToolbarSkills,
    ToolbarSettings,
    ToolbarLeave,
    ListNavigate,
    ListOpen,
    ListFocusNumber,
    ListScroll,
    ListSelectText,
    SessionCloseHoldD,
    SessionCloseEnter,
    SessionCloseMouse,
    SessionCloseConfirm,
    GroupFoldToggle,
    GroupExpandToggle,
    GroupDragReorder,
    ContextRename,
    ContextDelete,
    ContextCut,
    ContextCopy,
    ContextPaste,
    ContextSelectAll,
    RenameStart,
    RenameSave,
    RenameCancel,
    NotepadExpand,
    NotepadCollapse,
    NotepadFocus,
    NotepadPaste,
    NotepadCopy,
    NotepadContextMenu,
    QuickLaunchTerminal,
    QuickLaunchGrok,
    QuickLaunchClaude,
    QuickLaunchCodex,
    QuickLaunchOpencode,
    SidebarRefresh,
    SidebarSessionsTitleClick,
    SidebarAttach,
    SidebarDetach,
    LauncherOpen,
    LauncherClose,
    LauncherCancel,
    LauncherFieldWorkspace,
    LauncherFieldAgent,
    LauncherFieldModel,
    LauncherFieldPrompt,
    LauncherModeOpen,
    LauncherModeBackground,
    LauncherSubmit,
    SettingsOpen,
    SettingsSave,
    SettingsToggle,
    SettingsClose,
    CliUp,
    CliDown,
    CliDoctor,
    CliStatus,
    CliList,
    CliNew,
    CliGrok,
    CliCodex,
    CliOpencode,
    CliClaude,
    CliClose,
    CliLeave,
    CliFocus,
    CliRefresh,
    CliHooksSetup,
    CliHooksStatus,
    CliPanelNewSession,
    CliPanelSettings,
    CliTelemetryEnable,
    CliTelemetryDisable,
    CliTelemetryLog,
    CliTelemetryExport,
    CliUpgrade,
    CliUpgradeCheck,
    LifecycleInstallCompleted,
    LifecycleUpgradeCompleted,
    LifecycleUninstall,
    UpdateBannerDismiss,
    UpdateBannerUpgrade,
}

impl FeatureId {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ToolbarNewSession => "toolbar.new_chat",
            Self::ToolbarSearch => "toolbar.search",
            Self::ToolbarAutomations => "toolbar.automations",
            Self::ToolbarMcps => "toolbar.mcps",
            Self::ToolbarSkills => "toolbar.skills",
            Self::ToolbarSettings => "toolbar.settings",
            Self::ToolbarLeave => "toolbar.leave",
            Self::ListNavigate => "list.navigate",
            Self::ListOpen => "list.open",
            Self::ListFocusNumber => "list.focus_number",
            Self::ListScroll => "list.scroll",
            Self::ListSelectText => "list.select_text",
            Self::SessionCloseHoldD => "session.close_hold_d",
            Self::SessionCloseEnter => "session.close_enter",
            Self::SessionCloseMouse => "session.close_mouse",
            Self::SessionCloseConfirm => "session.close_confirm",
            Self::GroupFoldToggle => "group.fold_toggle",
            Self::GroupExpandToggle => "group.expand_toggle",
            Self::GroupDragReorder => "group.drag_reorder",
            Self::ContextRename => "context.rename",
            Self::ContextDelete => "context.delete",
            Self::ContextCut => "context.cut",
            Self::ContextCopy => "context.copy",
            Self::ContextPaste => "context.paste",
            Self::ContextSelectAll => "context.select_all",
            Self::RenameStart => "rename.start",
            Self::RenameSave => "rename.save",
            Self::RenameCancel => "rename.cancel",
            Self::NotepadExpand => "notepad.expand",
            Self::NotepadCollapse => "notepad.collapse",
            Self::NotepadFocus => "notepad.focus",
            Self::NotepadPaste => "notepad.paste",
            Self::NotepadCopy => "notepad.copy",
            Self::NotepadContextMenu => "notepad.context_menu",
            Self::QuickLaunchTerminal => "quick_launch.terminal",
            Self::QuickLaunchGrok => "quick_launch.grok",
            Self::QuickLaunchClaude => "quick_launch.claude",
            Self::QuickLaunchCodex => "quick_launch.codex",
            Self::QuickLaunchOpencode => "quick_launch.opencode",
            Self::SidebarRefresh => "sidebar.refresh",
            Self::SidebarSessionsTitleClick => "sidebar.sessions_title_click",
            Self::SidebarAttach => "sidebar.attach",
            Self::SidebarDetach => "sidebar.detach",
            Self::LauncherOpen => "launcher.open",
            Self::LauncherClose => "launcher.close",
            Self::LauncherCancel => "launcher.cancel",
            Self::LauncherFieldWorkspace => "launcher.field.workspace",
            Self::LauncherFieldAgent => "launcher.field.agent",
            Self::LauncherFieldModel => "launcher.field.model",
            Self::LauncherFieldPrompt => "launcher.field.prompt",
            Self::LauncherModeOpen => "launcher.mode.open",
            Self::LauncherModeBackground => "launcher.mode.background",
            Self::LauncherSubmit => "launcher.submit",
            Self::SettingsOpen => "settings.open",
            Self::SettingsSave => "settings.save",
            Self::SettingsToggle => "settings.toggle",
            Self::SettingsClose => "settings.close",
            Self::CliUp => "cli.up",
            Self::CliDown => "cli.down",
            Self::CliDoctor => "cli.doctor",
            Self::CliStatus => "cli.status",
            Self::CliList => "cli.list",
            Self::CliNew => "cli.new",
            Self::CliGrok => "cli.grok",
            Self::CliCodex => "cli.codex",
            Self::CliOpencode => "cli.opencode",
            Self::CliClaude => "cli.claude",
            Self::CliClose => "cli.close",
            Self::CliLeave => "cli.leave",
            Self::CliFocus => "cli.focus",
            Self::CliRefresh => "cli.refresh",
            Self::CliHooksSetup => "cli.hooks_setup",
            Self::CliHooksStatus => "cli.hooks_status",
            Self::CliPanelNewSession => "cli.panel_new_chat",
            Self::CliPanelSettings => "cli.panel_settings",
            Self::CliTelemetryEnable => "cli.telemetry_enable",
            Self::CliTelemetryDisable => "cli.telemetry_disable",
            Self::CliTelemetryLog => "cli.telemetry_log",
            Self::CliTelemetryExport => "cli.telemetry_export",
            Self::CliUpgrade => "cli.upgrade",
            Self::CliUpgradeCheck => "cli.upgrade_check",
            Self::LifecycleInstallCompleted => "lifecycle.install_completed",
            Self::LifecycleUpgradeCompleted => "lifecycle.upgrade_completed",
            Self::LifecycleUninstall => "lifecycle.uninstall",
            Self::UpdateBannerDismiss => "update.banner_dismiss",
            Self::UpdateBannerUpgrade => "update.banner_upgrade",
        }
    }

    pub fn all_ids() -> &'static [&'static str] {
        &[
            "toolbar.new_chat",
            "toolbar.search",
            "toolbar.automations",
            "toolbar.mcps",
            "toolbar.skills",
            "toolbar.settings",
            "toolbar.leave",
            "list.navigate",
            "list.open",
            "list.focus_number",
            "list.scroll",
            "list.select_text",
            "session.close_hold_d",
            "session.close_enter",
            "session.close_mouse",
            "session.close_confirm",
            "group.fold_toggle",
            "group.expand_toggle",
            "group.drag_reorder",
            "context.rename",
            "context.delete",
            "context.cut",
            "context.copy",
            "context.paste",
            "context.select_all",
            "rename.start",
            "rename.save",
            "rename.cancel",
            "notepad.expand",
            "notepad.collapse",
            "notepad.focus",
            "notepad.paste",
            "notepad.copy",
            "notepad.context_menu",
            "quick_launch.terminal",
            "quick_launch.grok",
            "quick_launch.claude",
            "quick_launch.codex",
            "quick_launch.opencode",
            "sidebar.refresh",
            "sidebar.sessions_title_click",
            "sidebar.attach",
            "sidebar.detach",
            "launcher.open",
            "launcher.close",
            "launcher.cancel",
            "launcher.field.workspace",
            "launcher.field.agent",
            "launcher.field.model",
            "launcher.field.prompt",
            "launcher.mode.open",
            "launcher.mode.background",
            "launcher.submit",
            "settings.open",
            "settings.save",
            "settings.toggle",
            "settings.close",
            "cli.up",
            "cli.down",
            "cli.doctor",
            "cli.status",
            "cli.list",
            "cli.new",
            "cli.grok",
            "cli.codex",
            "cli.opencode",
            "cli.claude",
            "cli.close",
            "cli.leave",
            "cli.focus",
            "cli.refresh",
            "cli.hooks_setup",
            "cli.hooks_status",
            "cli.panel_new_chat",
            "cli.panel_settings",
            "cli.telemetry_enable",
            "cli.telemetry_disable",
            "cli.telemetry_log",
            "cli.telemetry_export",
            "cli.upgrade",
            "cli.upgrade_check",
            "lifecycle.install_completed",
            "lifecycle.upgrade_completed",
            "lifecycle.uninstall",
            "update.banner_dismiss",
            "update.banner_upgrade",
        ]
    }
}

impl Serialize for FeatureId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for FeatureId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        let id = value.as_str();
        FeatureId::all_ids()
            .iter()
            .find_map(|&known| {
                if known == id {
                    Some(match id {
                        "toolbar.new_chat" => Self::ToolbarNewSession,
                        "toolbar.search" => Self::ToolbarSearch,
                        "toolbar.automations" => Self::ToolbarAutomations,
                        "toolbar.mcps" => Self::ToolbarMcps,
                        "toolbar.skills" => Self::ToolbarSkills,
                        "toolbar.settings" => Self::ToolbarSettings,
                        "toolbar.leave" => Self::ToolbarLeave,
                        "list.navigate" => Self::ListNavigate,
                        "list.open" => Self::ListOpen,
                        "list.focus_number" => Self::ListFocusNumber,
                        "list.scroll" => Self::ListScroll,
                        "list.select_text" => Self::ListSelectText,
                        "session.close_hold_d" => Self::SessionCloseHoldD,
                        "session.close_enter" => Self::SessionCloseEnter,
                        "session.close_mouse" => Self::SessionCloseMouse,
                        "session.close_confirm" => Self::SessionCloseConfirm,
                        "group.fold_toggle" => Self::GroupFoldToggle,
                        "group.expand_toggle" => Self::GroupExpandToggle,
                        "group.drag_reorder" => Self::GroupDragReorder,
                        "context.rename" => Self::ContextRename,
                        "context.delete" => Self::ContextDelete,
                        "context.cut" => Self::ContextCut,
                        "context.copy" => Self::ContextCopy,
                        "context.paste" => Self::ContextPaste,
                        "context.select_all" => Self::ContextSelectAll,
                        "rename.start" => Self::RenameStart,
                        "rename.save" => Self::RenameSave,
                        "rename.cancel" => Self::RenameCancel,
                        "notepad.expand" => Self::NotepadExpand,
                        "notepad.collapse" => Self::NotepadCollapse,
                        "notepad.focus" => Self::NotepadFocus,
                        "notepad.paste" => Self::NotepadPaste,
                        "notepad.copy" => Self::NotepadCopy,
                        "notepad.context_menu" => Self::NotepadContextMenu,
                        "quick_launch.terminal" => Self::QuickLaunchTerminal,
                        "quick_launch.grok" => Self::QuickLaunchGrok,
                        "quick_launch.claude" => Self::QuickLaunchClaude,
                        "quick_launch.codex" => Self::QuickLaunchCodex,
                        "quick_launch.opencode" => Self::QuickLaunchOpencode,
                        "sidebar.refresh" => Self::SidebarRefresh,
                        "sidebar.sessions_title_click" => Self::SidebarSessionsTitleClick,
                        "sidebar.attach" => Self::SidebarAttach,
                        "sidebar.detach" => Self::SidebarDetach,
                        "launcher.open" => Self::LauncherOpen,
                        "launcher.close" => Self::LauncherClose,
                        "launcher.cancel" => Self::LauncherCancel,
                        "launcher.field.workspace" => Self::LauncherFieldWorkspace,
                        "launcher.field.agent" => Self::LauncherFieldAgent,
                        "launcher.field.model" => Self::LauncherFieldModel,
                        "launcher.field.prompt" => Self::LauncherFieldPrompt,
                        "launcher.mode.open" => Self::LauncherModeOpen,
                        "launcher.mode.background" => Self::LauncherModeBackground,
                        "launcher.submit" => Self::LauncherSubmit,
                        "settings.open" => Self::SettingsOpen,
                        "settings.save" => Self::SettingsSave,
                        "settings.toggle" => Self::SettingsToggle,
                        "settings.close" => Self::SettingsClose,
                        "cli.up" => Self::CliUp,
                        "cli.down" => Self::CliDown,
                        "cli.doctor" => Self::CliDoctor,
                        "cli.status" => Self::CliStatus,
                        "cli.list" => Self::CliList,
                        "cli.new" => Self::CliNew,
                        "cli.grok" => Self::CliGrok,
                        "cli.codex" => Self::CliCodex,
                        "cli.opencode" => Self::CliOpencode,
                        "cli.claude" => Self::CliClaude,
                        "cli.close" => Self::CliClose,
                        "cli.leave" => Self::CliLeave,
                        "cli.focus" => Self::CliFocus,
                        "cli.refresh" => Self::CliRefresh,
                        "cli.hooks_setup" => Self::CliHooksSetup,
                        "cli.hooks_status" => Self::CliHooksStatus,
                        "cli.panel_new_chat" => Self::CliPanelNewSession,
                        "cli.panel_settings" => Self::CliPanelSettings,
                        "cli.telemetry_enable" => Self::CliTelemetryEnable,
                        "cli.telemetry_disable" => Self::CliTelemetryDisable,
                        "cli.telemetry_log" => Self::CliTelemetryLog,
                        "cli.telemetry_export" => Self::CliTelemetryExport,
                        "cli.upgrade" => Self::CliUpgrade,
                        "cli.upgrade_check" => Self::CliUpgradeCheck,
                        "lifecycle.install_completed" => Self::LifecycleInstallCompleted,
                        "lifecycle.upgrade_completed" => Self::LifecycleUpgradeCompleted,
                        "lifecycle.uninstall" => Self::LifecycleUninstall,
                        "update.banner_dismiss" => Self::UpdateBannerDismiss,
                        "update.banner_upgrade" => Self::UpdateBannerUpgrade,
                        _ => return None,
                    })
                } else {
                    None
                }
            })
            .ok_or_else(|| serde::de::Error::custom(format!("unknown feature id: {value}")))
    }
}
