use crate::bar::notepad::Note;
use crate::bar::ui::ToolbarAction;

/// Dirty-tracking snapshot of the last drawn sidebar frame.
pub(crate) struct RenderCache {
    pub rows_version: u64,
    pub size: Option<(u16, u16)>,
    pub scroll: Option<usize>,
    pub close_mode: bool,
    pub hover_row: Option<usize>,
    pub close_target_row: Option<usize>,
    pub anim_frame: Option<usize>,
    pub group_hover_row: Option<usize>,
    pub toolbar_hover: Option<ToolbarAction>,
    pub coming_soon_frames: Vec<(ToolbarAction, usize)>,
    pub settings_hover: bool,
    pub leave_hover: bool,
    pub workspace_settings_open: bool,
    pub workspace_new_session_open: bool,
    pub workspace_automations_open: bool,
    pub workspace_mcps_open: bool,
    pub workspace_skills_open: bool,
    pub sessions_expanded: bool,
    pub notepad_expanded: bool,
    pub notes_list_expanded: bool,
    pub notepad_focused: bool,
    pub notes: Vec<Note>,
    pub active_note_id: Option<String>,
    pub notepad_cursor: usize,
    pub notepad_scroll: usize,
    pub notepad_section_header_hover: bool,
    pub notepad_section_add_hover: bool,
    pub notepad_note_hover: Option<usize>,
    pub notepad_selection: Option<(usize, usize)>,
    pub sessions_title_hover: bool,
    pub sessions_title_add_hover: bool,
    pub collapse_control_hover: bool,
    /// Last painted rail vs full-list mode. `None` until the first paint.
    /// Tracked separately because rail mode can flip without a rows_version or
    /// size change (rapid toggle while pane width has not settled yet).
    pub sidebar_rail: Option<bool>,
    pub clipboard_notice: Option<String>,
    pub update_banner: Option<String>,
    pub update_upgrade_hover: bool,
    pub update_dismiss_hover: bool,
    pub notepad_save_badge: Option<String>,
}

impl Default for RenderCache {
    fn default() -> Self {
        Self {
            rows_version: u64::MAX,
            size: None,
            scroll: None,
            close_mode: false,
            hover_row: None,
            close_target_row: None,
            anim_frame: None,
            group_hover_row: None,
            toolbar_hover: None,
            coming_soon_frames: Vec::new(),
            settings_hover: false,
            leave_hover: false,
            workspace_settings_open: false,
            workspace_new_session_open: false,
            workspace_automations_open: false,
            workspace_mcps_open: false,
            workspace_skills_open: false,
            sessions_expanded: false,
            notepad_expanded: false,
            notes_list_expanded: false,
            notepad_focused: false,
            notes: Vec::new(),
            active_note_id: None,
            notepad_cursor: 0,
            notepad_scroll: 0,
            notepad_section_header_hover: false,
            notepad_section_add_hover: false,
            notepad_note_hover: None,
            notepad_selection: None,
            sessions_title_hover: false,
            sessions_title_add_hover: false,
            collapse_control_hover: false,
            sidebar_rail: None,
            clipboard_notice: None,
            update_banner: None,
            update_upgrade_hover: false,
            update_dismiss_hover: false,
            notepad_save_badge: None,
        }
    }
}
